Console.Clear();
Console.Write("координату х1: ");
double x1 = Convert.ToDouble(Console.ReadLine());
Console.Write("координату y1: ");
double y1 = Convert.ToDouble(Console.ReadLine());
Console.Write("координату х2: ");
double x2 = Convert.ToDouble(Console.ReadLine());
Console.Write("координату y2: ");
double y2 = Convert.ToDouble(Console.ReadLine());
double l = Math.Round(Math.Sqrt(Math.Pow(x2-x1,2)+Math.Pow(y2-y1,2)));
Console.Write(l);